version: '3.1'

volumes:
  pg:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5555}:5432
